version: '3'
services:
  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8080:7070"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: --verbose